['manufacture_year',
 'engine_capacity',
 'mileage',
 'brand_BMW',
 'brand_Cadillac',
 'brand_Changan',
 'brand_Chery',
 'brand_DFSK',
 'brand_Daihatsu',
 'brand_Fiat',
 'brand_Ford',
 'brand_Geely',
 'brand_Great Wall',
 'brand_Haval',
 'brand_Honda',
 'brand_Hyundai',
 'brand_Infiniti',
 'brand_Isuzu',
 'brand_JMC',
 'brand_Jaguar',
 'brand_Jeep',
 'brand_Kia',
 'brand_Land Rover',
 'brand_Lexus',
 'brand_Mahindra',
 'brand_Maruti Suzuki',
 'brand_Mazda',
 'brand_Mercedes-Benz',
 'brand_Mitsubishi',
 'brand_Nissan',
 'brand_Other brand',
 'brand_Porsche',
 'brand_Proton',
 'brand_Range Rover',
 'brand_SsangYong',
 'brand_Subaru',
 'brand_Suzuki',
 'brand_Tata',
 'brand_Toyota',
 'brand_Volkswagen',
 'brand_Zotye',
 'model_2000GT',
 'model_3 Series',
 'model_400',
 'model_5 Series',
 'model_520d',
 'model_525i',
 'model_640i',
 'model_7 Series',
 'model_730li',
 'model_800',
 'model_86',
 'model_A4',
 'model_A6',
 'model_A8',
 'model_ASX',
 'model_Accent',
 'model_Accord',
 'model_Airwave',
 'model_Allex',
 'model_Allion',
 'model_Alphard',
 'model_Alto',
 'model_Alto 800',
 'model_Aqua',
 'model_Attrage',
 'model_Auris',
 'model_Avanza',
 'model_Axela',
 'model_Axio',
 'model_Aygo',
 'model_B160',
 'model_Belta',
 'model_Bluebird',
 'model_C-Class',
 'model_C-HR',
 'model_CLA-Class',
 'model_CLK-Class',
 'model_CR-V',
 'model_CR-X',
 'model_CR-Z',
 'model_CT',
 'model_CX-3',
 'model_CX-7',
 'model_Cami',
 'model_Camry',
 'model_Caravan',
 'model_Carina',
 'model_Carryboy',
 'model_Cefiro',
 'model_Celica',
 'model_Challenger',
 'model_Chaser',
 'model_Ciaz',
 'model_City',
 'model_Civic',
 'model_Copen',
 'model_Corolla',
 'model_Corolla Cross',
 'model_Corona',
 'model_Corsa',
 'model_Cross',
 'model_Crown',
 'model_Cube',
 'model_Defender',
 'model_Demio',
 'model_Diesel',
 'model_Dyna',
 'model_E 240',
 'model_E 250',
 'model_E-Class',
 'model_Echo',
 'model_Eclipse Cross',
 'model_Eco Sport',
 'model_Ecosport',
 'model_Elantra',
 'model_Elgrand',
 'model_Esquire',
 'model_Esteem',
 'model_Estima',
 'model_Evoque',
 'model_Exiv',
 'model_Exora',
 'model_F-Type',
 'model_Fielder',
 'model_Fiesta',
 'model_Fit',
 'model_Freed',
 'model_GL-Class',
 'model_GLB 200',
 'model_GLC-Class',
 'model_GLE-Class',
 'model_GLS-Class',
 'model_GLX',
 'model_Galant',
 'model_Glory I-Auto',
 'model_Grace',
 'model_Grand Vitara',
 'model_H1',
 'model_H2',
 'model_H6',
 'model_HR-V',
 'model_HS 250h',
 'model_Hardbody Truck',
 'model_Harrier',
 'model_HiClass',
 'model_Hiace',
 'model_Highlander',
 'model_Hilux',
 'model_Hustler',
 'model_Indigo',
 'model_Indigo Ecs',
 'model_Insight',
 'model_Isis',
 'model_Jazz',
 'model_Jimny',
 'model_Jolion',
 'model_Juke',
 'model_Kluger',
 'model_LX',
 'model_Lancer',
 'model_Land Cruiser',
 'model_Liana',
 'model_LiteAce',
 'model_M-Class',
 'model_M3',
 'model_MR2',
 'model_MX-5',
 'model_March',
 'model_Mark II',
 'model_Mark X',
 'model_Mirage',
 'model_Mondeo',
 'model_Murano',
 'model_NX',
 'model_Nano',
 'model_Navara',
 'model_Noah',
 'model_Optima',
 'model_Other Model',
 'model_Other model',
 'model_Outlandar',
 'model_Outlander',
 'model_Pajero',
 'model_Paseo',
 'model_Passat',
 'model_Passo',
 'model_Patrol',
 'model_Platz',
 'model_Prado',
 'model_Premio',
 'model_Preve',
 'model_Prius',
 'model_Probox',
 'model_Progrès',
 'model_Q7',
 'model_QQ',
 'model_Quanto',
 'model_RAV4',
 'model_RX',
 'model_RX-8',
 'model_Ractis',
 'model_Ranger',
 'model_Raum',
 'model_Rexton',
 'model_Rocky',
 'model_Rogue',
 'model_RunX',
 'model_Rush',
 'model_S-Class',
 'model_SX4 S-Cross',
 'model_Saga',
 'model_Santa Fe',
 'model_Santafi',
 'model_Siena',
 'model_Sienna',
 'model_Sienta',
 'model_Soarer',
 'model_Solio',
 'model_Sonata',
 'model_Sorento',
 'model_Spacio',
 'model_Sport',
 'model_Sportage',
 'model_Sprinter',
 'model_Starlet',
 'model_Starlet Soleil',
 'model_Succeed',
 'model_Sunny',
 'model_Swift',
 'model_Sylphy',
 'model_T100',
 'model_TUV300',
 'model_Teana',
 'model_Tercel',
 'model_Terios',
 'model_Terracan',
 'model_Tiago',
 'model_Tiggo',
 'model_Tiida',
 'model_TownAce',
 'model_ToyoAce',
 'model_Trooper',
 'model_Tucson',
 'model_Uno',
 'model_Urvan',
 'model_V6',
 'model_Vanette',
 'model_Verossa',
 'model_Vezel',
 'model_Vigus 5',
 'model_Vios',
 'model_Vista',
 'model_Vitara',
 'model_Vitz',
 'model_Voxy',
 'model_Wagon R',
 'model_WagonR',
 'model_Wingroad',
 'model_Wish',
 'model_X Assista',
 'model_X-Pander',
 'model_X-Trail',
 'model_X1',
 'model_X3',
 'model_X5',
 'model_X7',
 'model_Xcent',
 'model_Yaris',
 'model_Yaris Cross',
 'model_Zen',
 'model_Zen Estilo',
 'model_i10',
 'model_ist',
 'model_l200',
 'model_l300',
 'condition_Used',
 'transmission_Manual',
 'transmission_Reconditioned',
 'body_type_Convertible',
 'body_type_Coupé/Sports',
 'body_type_Estate',
 'body_type_Hatchback',
 'body_type_MPV',
 'body_type_SUV / 4x4',
 'body_type_Saloon',
 'fuel_type_CNG, Electric',
 'fuel_type_CNG, LPG',
 'fuel_type_CNG, LPG, Other fuel type',
 'fuel_type_CNG, Octane',
 'fuel_type_CNG, Octane, LPG',
 'fuel_type_CNG, Octane, LPG, Other fuel type',
 'fuel_type_CNG, Octane, Other fuel type',
 'fuel_type_CNG, Other fuel type',
 'fuel_type_Diesel',
 'fuel_type_Diesel, CNG',
 'fuel_type_Diesel, Hybrid',
 'fuel_type_Diesel, Hybrid, Octane',
 'fuel_type_Diesel, LPG',
 'fuel_type_Diesel, Octane',
 'fuel_type_Diesel, Petrol, CNG, Hybrid, LPG',
 'fuel_type_Diesel, Petrol, CNG, Octane',
 'fuel_type_Diesel, Petrol, CNG, Octane, LPG',
 'fuel_type_Diesel, Petrol, LPG',
 'fuel_type_Diesel, Petrol, Octane',
 'fuel_type_Electric',
 'fuel_type_Electric, LPG',
 'fuel_type_Electric, Octane',
 'fuel_type_Hybrid',
 'fuel_type_Hybrid, Electric',
 'fuel_type_Hybrid, Electric, Octane',
 'fuel_type_Hybrid, Octane',
 'fuel_type_Hybrid, Octane, LPG',
 'fuel_type_LPG',
 'fuel_type_Octane',
 'fuel_type_Octane, LPG',
 'fuel_type_Octane, Other fuel type',
 'fuel_type_Other fuel type',
 'fuel_type_Petrol',
 'fuel_type_Petrol, CNG',
 'fuel_type_Petrol, CNG, Electric, Octane',
 'fuel_type_Petrol, CNG, LPG',
 'fuel_type_Petrol, CNG, Octane',
 'fuel_type_Petrol, CNG, Octane, LPG',
 'fuel_type_Petrol, CNG, Octane, Other fuel type',
 'fuel_type_Petrol, Electric, Octane',
 'fuel_type_Petrol, Hybrid',
 'fuel_type_Petrol, Hybrid, Electric, Octane',
 'fuel_type_Petrol, Hybrid, Electric, Other fuel type',
 'fuel_type_Petrol, Hybrid, LPG',
 'fuel_type_Petrol, Hybrid, Octane',
 'fuel_type_Petrol, LPG',
 'fuel_type_Petrol, Octane',
 'fuel_type_Petrol, Octane, LPG',
 'fuel_type_Petrol, Other fuel type',
 'owner_info_Not MEMBER',
 'AC_system_Non-Air Conditioned',
 'Accident_history_Unknown',
 'Camera_facility_Rare camera',
 'Light_facility_LED Backlight',
 'Light_facility_LED Headlight',
 'Light_facility_No LED']